<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="4" hostname="JeevaLaptop" failures="0" tests="1" name="Default test" time="3.573" errors="0" timestamp="2025-04-16T17:13:52 CDT">
  <testcase classname="swaglab_test.BaseClass" name="@AfterTest CloseExcel" time="0.001">
    <failure type="java.io.IOException" message="Cannot write data, document seems to have been closed already">
      <![CDATA[java.io.IOException: Cannot write data, document seems to have been closed already
at org.apache.poi.ooxml.POIXMLDocument.write(POIXMLDocument.java:230)
at swaglab_test.BaseClass.CloseExcel(BaseClass.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:71)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:400)
at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:333)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:657)
at org.testng.TestRunner.afterRun(TestRunner.java:845)
at org.testng.TestRunner.run(TestRunner.java:618)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- @AfterTest CloseExcel -->
  <testcase classname="swaglab_test.LoginTest" name="LockedUserLoginFailureTestFromExcel" time="0.539"/>
  <testcase classname="swaglab_test.LoginTest" name="LockedUserLoginFailureTest" time="0.0">
    <ignored/>
  </testcase> <!-- LockedUserLoginFailureTest -->
  <testcase classname="swaglab_test.LoginTest" name="LoginFailureTest" time="0.0">
    <ignored/>
  </testcase> <!-- LoginFailureTest -->
  <testcase classname="swaglab_test.LoginTest" name="LockedUserLoginFailureTestFromProperties" time="0.0">
    <ignored/>
  </testcase> <!-- LockedUserLoginFailureTestFromProperties -->
  <testcase classname="swaglab_test.LoginTest" name="LoginSuccessTest" time="0.0">
    <ignored/>
  </testcase> <!-- LoginSuccessTest -->
</testsuite> <!-- Default test -->
